### ISSUE TITLE
重复造轮子，还不起作用

### ISSUE THREAD

**Issue by wangqi-jeffrey** [itfsw/mybatis-generator-plugin#105]
<xml>
    
    <plugin type="com.itfsw.mybatis.generator.plugins.TableRenameConfigurationPlugin">
        <property name="domainObjectRenamingRule.searchString" value="^T"/>
        <property name="domainObjectRenamingRule.replaceString" value=""/>
    </plugin>
    
    <table tableName="tb">
        
        <property name="domainObjectRenamingRule.disable" value="true"/>
    </table>
    
    <table tableName="tb_ts1">
        
        <domainObjectRenamingRule searchString="^Tb" replaceString="B"/>
    </table>
</xml>

和官方提供的domainObjectRenamingRule属性作用基本一样，根本不用做全局配置，要生成所有表的实体，只需要tableName="t_%"做个全局匹配就行，然后使用官方提供的domainObjectRenamingRule属性，而且还有个问题，像t_user能正常生成User.java实体，如果是t_user_info，最后生成的竟然是Userinfo，不符合驼峰命名的规范，希望能解决下这个问题。

**Comment by itfsw** [comment]
编写插件时官方还没有没有domainObjectRenamingRule这个配置选项，所以当时为了方便进行表的重命名写了这个插件，至于有了domainObjectRenamingRule之后是因为官方那个没有全局替换所以增加了一个全局功能。至于驼峰命名那个请到官方提bug,之前已经给官方反馈过了（不想替换官方实现，这个插件只是单纯为其增加了一个全局替换功能）。
