### ISSUE TITLE
13. 自定义注释插件 复制模板到idea文件导致格式混乱的问题

### ISSUE THREAD

**Issue by mathcoder23** [itfsw/mybatis-generator-plugin#19]
##  复制模板到idea文件导致格式混乱的问题
> 由于idea的原因，模板中的文本复制过去会被转换，导致生成注释格式混乱  
* 建议提供模板文件的下载地址，或者插件默认加载默认的模板文件
* 临时解决方案，可以不使用idea粘贴文件，用最基本的文本编辑器粘贴模板文件。

**Comment by itfsw** [comment]
已经在说明文档中增加了默认模板地址，谢谢反馈！
