### ISSUE TITLE
1.1.2中有Bug

### ISSUE THREAD

**Issue by wenfuqiang** [itfsw/mybatis-generator-plugin#21]
指定了逻辑删除列，且配置有rootClass的情况下，还是直接取bean中的删除列字段
这时删除列在rootClass中，是private属性，不能直接引用的

**Comment by itfsw** [comment]
”这时删除列在rootClass中，是private属性，不能直接引用的“ 删除列在rootClass是什么意思呢？

**Comment by itfsw** [comment]
没有问题啊，你检查下你RootClass是否符合要求 
![qq 20180420205351](https://user-images.githubusercontent.com/24953508/39051988-fe63c9b4-44dc-11e8-95f5-9c51dce4a224.jpg)

**Comment by wenfuqiang** [comment]
哦，我大概知道是什么原因了：RootClass不在运行时的classpath中。

顺便请教下，你生成代码时，RootClass是放在哪里的，那个Maven-Project->Mybatis Generate ->Run , 好像 没有地方指定ClassPath



在 2018-04-20 20:54:36，"何伟" <notifications@github.com> 写道：


没有问题啊，你检查下你RootClass是否符合要求

**Comment by itfsw** [comment]
就在Maven项目中，我不知道你用的具体是哪个开发工具，这边我常用的idea是正常识别的。

**Comment by wenfuqiang** [comment]
![image](https://user-images.githubusercontent.com/31055278/39339940-d04f5982-49fd-11e8-993d-da8dc4c29eaa.png)

我是在这里执行的，RootClass在OwnerCloud.domain中有，在这里执行生成代码，找不到RootClass类
