### ISSUE TITLE
配置设置允许修改时，Mapper 文件中出现了 ID 相同的 SQL 

### ISSUE THREAD

**Issue by rxhaol** [itfsw/mybatis-generator-plugin#22]
# 环境列表

- MyBatis Generator : 1.1.2
-  JDK : 1.8.0_152
- Maven : 3.5.0

# 说明

Maven build 文件配置如下：
```
<configuration>
  <configurationFile>src/main/resources/mybatis_generator.xml</configurationFile>
  <verbose>true</verbose>
  <overwrite>true</overwrite>
</configuration>
```
当使用 Maven Generator 重新生成 Mapper 文件时，Mapper 文件会追加同名的 SQL 。如下面的图片所示：生成了同名的  `selectByExample` SQL。

**第一次生成 Mapper 文件：**

![one-match](https://user-images.githubusercontent.com/18501114/39106688-e9d03c5c-46ef-11e8-9352-f578e58584bc.png)

**第二次生成 Mapper 文件：**

![two-matches](https://user-images.githubusercontent.com/18501114/39106694-edb4c0f4-46ef-11e8-92a7-ec91483b3e1d.png)

**Comment by bonjourcs** [comment]
Java 代码是会被覆盖的，但是 XML 文件是追加的。

**Comment by itfsw** [comment]
不会啊，代码中会判断有 @mbg.generated 就会替换
![qq 20180423134451](https://user-images.githubusercontent.com/24953508/39108804-a3de2bf2-46fc-11e8-9eee-bd5e26abbd33.jpg)

**Comment by itfsw** [comment]
MyBatis Generator : 1.1.2 ？ 有点老了，是不是这个版本还没有实现这个？你可以试下升级下版本

**Comment by bonjourcs** [comment]
:smile:  这个 MyBatis Generator 的版本对应的是你的 Release 里的版本。不知道我的配置哪里有问题，生成的 `selectOneByExample` 有 `@mbg.generated` ，`selectByExample` 没有该注释。

**selectOneByExample**
![select-one](https://user-images.githubusercontent.com/18501114/39109193-64392ad6-46fe-11e8-8694-2bc4dba80d50.png)
**selectByExample**
![select](https://user-images.githubusercontent.com/18501114/39109200-6b05c6d0-46fe-11e8-94ad-b8c80b0eff0e.png)

**Comment by itfsw** [comment]
你检查下是不是你注释配置，问题应该还是出在那儿

**Comment by bonjourcs** [comment]
:grin: OK.多谢回复！
