### ISSUE TITLE
乐观锁插件

### ISSUE THREAD

**Issue by linlinjava** [itfsw/mybatis-generator-plugin#23]
并发更新应该引入乐观锁，原理是简单，基于version就可以，但是如果插件自动生成代码，那应该更方便了。

目前google结果是，mybatis项目本身对乐观锁提供了支持，然后以下mybatis项目好像支持乐观锁：
* https://github.com/Dreamroute/locker
* https://github.com/baomidou/mybatis-plus
* https://github.com/abel533/Mapper

第一个也是插件，但是我觉得代码有点复杂，不像本项目一样一个插件就是一个类，同时不支持maven；后面两个项目，我觉得会引入依赖，目前我觉得插件形式自动生成代码既简单又直观有效。

当前项目没有乐观锁插件，不知道作者在实际项目是是否有更好的解决方案，希望交流一下。

**Comment by itfsw** [comment]
已在[V1.2.0](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.2.0)版本引入乐观锁插件。
