### ISSUE TITLE
集成通用mapper时生成mapper出现问题

### ISSUE THREAD

**Issue by chanry** [itfsw/mybatis-generator-plugin#24]
由于集成了通用mapper（tk.mybatis），在生成table时需要把example关闭，如：
`<table tableName="t_user_info" domainObjectName="UserInfo" 
			enableCountByExample="false" enableUpdateByExample="false" enableDeleteByExample="false" 
			enableSelectByExample="false" selectByExampleQueryId="false">
		</table>`
但是设置为false之后生成的mapper没有import ibatis的Param：
 Param cannot be resolved to 
	 a type
请问楼主有集成过通用mapper吗？

**Comment by itfsw** [comment]
请问你是整合哪些插件出的问题呢？

**Comment by zheng-zy** [comment]
我这边也出现类似的问题，用的是一下插件
<plugin type="com.itfsw.mybatis.generator.plugins.SelectOneByExamplePlugin"/>
        
        <plugin type="com.itfsw.mybatis.generator.plugins.LimitPlugin"/>
        <plugin type="com.itfsw.mybatis.generator.plugins.ModelBuilderPlugin"/>
        
        <plugin type="com.itfsw.mybatis.generator.plugins.ModelColumnPlugin"/>
        
        <plugin type="com.itfsw.mybatis.generator.plugins.BatchInsertPlugin"/>

还有一个问题就是生成的mapper里面
CompanySongInfoKey selectOneByExample(com.ktvme.dao.CompanySongInfoExample example);
但是其实我domainObjectName="CompanySongInfo" 这个怎么解决，你这边有没有集成的例子给一个 可以直接使用的

**Comment by itfsw** [comment]
@zheng-zy CompanySongInfo 这个类是否只有主键呢？

**Comment by zheng-zy** [comment]
`private Integer companyid;
    private String songid;`
有两个字段  companyid是我的主键

**Comment by zheng-zy** [comment]
@itfsw `private Integer companyid;
    private String songid;`
有两个字段  companyid是我的主键

**Comment by itfsw** [comment]
@zheng-zy 不对啊，如果你数据库只有一个主键companyid是不会有CompanySongInfoKey 这个类的啊

**Comment by zheng-zy** [comment]
@itfsw 这个我也是百思不得其解，我原先不用插件就没有这个问题 还有就是生成的类使用的是Example结尾(com.ktvme.dao.CompanySongInfoExample example);  所以我想有没有简单的可以跑的demo

**Comment by itfsw** [comment]
@zheng-zy Example是mybatis generator定义的查询条件生成类的通用结尾，目前没有方法修改。至于CompanySongInfoKey这个按理是只有存在多个主键的情况下才会生成的，我提供的插件里只会去取这个类，你检查下你表结构呢。
```java
FullyQualifiedJavaType type;
        if (introspectedTable.getRules().generateBaseRecordClass()) {
            type = new FullyQualifiedJavaType(introspectedTable.getBaseRecordType());
        } else if (introspectedTable.getRules().generatePrimaryKeyClass()) {
            type = new FullyQualifiedJavaType(introspectedTable.getPrimaryKeyType());
        } else {
            throw new RuntimeException(getString("RuntimeError.12"));
        }
        return type;
```
你所描述的CompanySongInfoKey selectOneByExample(com.ktvme.dao.CompanySongInfoExample example);只可能在表只存在主键且主键个数大于1的情况下才可能发生。
importTypes那个问题是我之前考虑不周，这里提供的插件都没有考虑会禁用某些方法的情况下使用，这个我会尽快加上。

**Comment by zheng-zy** [comment]
@itfsw 我这个表是联合主键  是这个问题

**Comment by itfsw** [comment]
[V1.2.2](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.2.2)修复了在禁用某些方法生成时导致的Mapper没有正常import类导致的编译问题。
