### ISSUE TITLE
可以增加自动删除已经存在的mapper文件插件吗?

### ISSUE THREAD

**Issue by id4alex** [itfsw/mybatis-generator-plugin#25]
mybatis generator 的mapper xml文件每次重新生成的时候回导致重复的mapping 规则. 可否实现类似功能?

https://stackoverflow.com/questions/43245041/how-could-let-mybatis-generator-overwriting-the-already-generated-mapper-xml

**Comment by itfsw** [comment]
为什么会有重复规则呢？插件会根据注释中的@mbg.generated进行覆盖的

**Comment by id4alex** [comment]
额,刚才查阅了下文档, 你说的是对的.  不过前提是 不能开启 suppressAllComments.  

我这边遇到的情况是开了suppressAllComments,  然后每次generate的时候都会重新生成.

谢谢@itfsw 我这边关闭下这个issue.
