### ISSUE TITLE
批量插入的selective不太友好

### ISSUE THREAD

**Issue by yuyong725** [itfsw/mybatis-generator-plugin#28]
批量插入插件，batchInsertSelective不太友好，需要指定特定的列。可否使用原生xml的
`<if test="fielName != null">`
这种方式拼接

**Comment by itfsw** [comment]
之前考虑过这个问题，在不开启allowMultiQueries=true批量提交的情况下，insert 语句在指定列名称是无法确认的。
比如我第一个元素 tb.field1=null, tb.field2="ts1", 第二个元素 tb.field1=1,tb.field2="ts2"。sql insert需要指定列，我怎么去取列呢。
目前能够和原生一致的情况下只能allowMultiQueries=true，这样才能生成对应sql
```sql
insert into tb (field2) values ('ts1');insert into tb (field1, field2) values (1, 'ts1');
```
但allowMultiQueries=true情况下容易发生sql注入的风险，所以就没有做实现。

**Comment by itfsw** [comment]
[V1.2.5](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.2.5)已解决。

**Comment by yuyong725** [comment]
谢谢老板，赞
