### ISSUE TITLE
可以增加个批量的 插入存在便更新的插件

### ISSUE THREAD

**Issue by yanjinbin** [itfsw/mybatis-generator-plugin#29]
-- auto-generated definition
CREATE TABLE student
(
  id   INT AUTO_INCREMENT
  COMMENT '自增id'
    PRIMARY KEY,
  no   INT DEFAULT '0'        NOT NULL,
  type TINYINT DEFAULT '0'    NOT NULL,
  age  INT DEFAULT '0'        NOT NULL
  COMMENT '年龄',
  name VARCHAR(64) DEFAULT '' NOT NULL
  COMMENT '姓名',
  CONSTRAINT no
  UNIQUE (no, type)
)
  ENGINE = InnoDB;

-------

INSERT INTO test.student (id, no, type, age, name) VALUES (2, 15, 2, 100, 'AAACCC');
INSERT INTO test.student (id, no, type, age, name) VALUES (4, 12, 1, 9999, 'DDD');

--------
 ##### 增加如下操作功能???---- 现在是单条的 插入存在便更新的插件

INSERT INTO `student` (no, type, age, name) VALUES (15, 2, 100, "长者"), (12, 1, 9999, "香港记者")
ON DUPLICATE KEY UPDATE age = values(age), name = values(name)

**Comment by yanjinbin** [comment]
什么时候加呢  我打算先手写了 ,有空自己整了

**Comment by yanjinbin** [comment]
在 批量选择插入后面贴上这个就行  😀 
        on duplicate key update
        <foreach collection="selective" item="column" separator=",">
            ${column.value}=values(${column.value})
        </foreach>

**Comment by itfsw** [comment]
已经弄了，还没有打版本，你可以自己先下载打个临时用。

**Comment by itfsw** [comment]
[V1.2.5](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.2.5)已解决。

**Comment by yanjinbin** [comment]
666 谢谢老铁了

**Comment by yanjinbin** [comment]
还有能不能去掉一些不必要的注释 比如@project mbg 跟业务无关的字段  , 只保留ddl的comment

**Comment by itfsw** [comment]
你可以看那个自定义注释插件，除了mbg之外其他的你都可以去掉

**Comment by yanjinbin** [comment]
mapper方法没有 batchupdateinsertselective
