### ISSUE TITLE
逻辑删除有问题1.0.6

### ISSUE THREAD

**Issue by DomKing** [itfsw/mybatis-generator-plugin#3]
对于1.0.6实测，逻辑批量删除是问题的，因为用到了批量更新的sql，所以参数名都是example，但是因为Mapper文件中未加@param，导致执行时，会用XXXExample去找getExample的getter方法。会报错。实际在逻辑删除插件中，即使参数个数为1，也要加上@param。最后，感谢插件的提供

**Comment by itfsw** [comment]
十分感谢你的反馈，这个BUG不知道什么时候引入的，在低版本上也发现了该问题，但低版本是之前经过测试的，所以引入原因还是未知，再次感谢你的反馈。[Mybatis Generator Plugin Realease 1.0.8](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.0.8)
同时再次吐槽GitHub的邮件问题，一直不能收到该邮件，，，，，，，，，，，，，，，，

**Comment by DomKing** [comment]
感谢你的开源贡献，以及对我的帮助。最近梯子被伙搞坏了，现在才回复。

2017-05-10 10:48 GMT+08:00 何伟 <notifications@github.com>:
