### ISSUE TITLE
tb表会生产andLogicalDeleted？

### ISSUE THREAD

**Issue by linlinjava** [itfsw/mybatis-generator-plugin#30]
基于1.2.4，在tb表中增加了deleted属性，然后采用逻辑删除插件生产代码。

Tb类存在deleted域，存在getDeleted和setDeleted方法了。
但是tb表会多生产andLogicalDeleted方法，我不知道这里这个方法为什么要存在？
有什么作用吗，还是放错地方了。

```
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }
```

**Comment by itfsw** [comment]
这个方法是setDeleted的简写，快速赋值逻辑删除列。

**Comment by linlinjava** [comment]
好的，明白了，大概是有的人是用其他数值标识删除状态。

就我而言，我数据库采用bit1标识，mybatis generator会自动把java代码中的deleted域设置boolean，因此可能不需要这个特性。而且，我觉得这样的实践也很好。

所以这个能不能设计成可选:)

**Comment by itfsw** [comment]
好的，谢谢反馈。
