### ISSUE TITLE
关于mysql驱动支持

### ISSUE THREAD

**Issue by zhangyy3** [itfsw/mybatis-generator-plugin#35]
https://github.com/itfsw/mybatis-generator-plugin/blob/master/src/main/java/com/itfsw/mybatis/generator/plugins/BatchInsertPlugin.java

`// 插件使用前提是数据库为MySQL或者SQLserver，因为返回主键使用了JDBC的getGenereatedKeys方法获取主键
        if ("com.mysql.jdbc.Driver".equalsIgnoreCase(this.getContext().getJdbcConnectionConfiguration().getDriverClass()) == false
                && "com.microsoft.jdbc.sqlserver.SQLServer".equalsIgnoreCase(this.getContext().getJdbcConnectionConfiguration().getDriverClass()) == false
                && "com.microsoft.sqlserver.jdbc.SQLServerDriver".equalsIgnoreCase(this.getContext().getJdbcConnectionConfiguration().getDriverClass()) == false) {
            warnings.add("itfsw:插件" + this.getClass().getTypeName() + "插件使用前提是数据库为MySQL或者SQLserver，因为返回主键使用了JDBC的getGenereatedKeys方法获取主键！");
            return false;
        }`

这个地方，com.mysql.cj.jdbc.Driver ，新的驱动类型不支持。

**Comment by itfsw** [comment]
[V1.2.10](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.2.10)已修正
