### ISSUE TITLE
能不能提一个BaseDomain和BaseExample类

### ISSUE THREAD

**Issue by hackbaby** [itfsw/mybatis-generator-plugin#37]
1.能不能提取一个BaseExample类，存放Criteria  这样减少很多重复代码，并且提取了一个抽象，然后统一的查询条件Criteria，可以被使用到多个表查询中。
2.改写andEqual方法，这样代码的复用性更强
      之前：  public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }
        之后：public Criteria and(String column,Object value){
            addCriterion(column+" =", value, column);
            return (Criteria) this; 
        }

**Comment by itfsw** [comment]
这个涉及更改官方工具的核心逻辑了，这里提供的一系列插件的目的是在官方基础上去丰富和完善插件功能，所以暂时不会去动他的核心逻辑。
