### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by HugoLew** [itfsw/mybatis-generator-plugin#38]
在README.md文件中关于逻辑删除插件使用说明有处错误，
配置逻辑删除常量名称的name错了，会导致生成的实体类中的值都是false。

这是原来的

        
        <property name="logicalDeleteValue" value="DEL"/>
        
        <property name="logicalUnDeleteValue" value="UN_DEL"/>

应改为

            
            <property name="logicalDeleteConstName" value="IS_DELETED"/>
            
            <property name="logicalUnDeleteConstName" value="NOT_DELETED"/>

**Comment by itfsw** [comment]
已收到，谢谢反馈！

**Comment by HugoLew** [comment]
是name里面的值不对
logicalDeleteValue->logicalDeleteConstName
logicalUnDeleteValue->logicalUnDeleteConstName

**Comment by itfsw** [comment]
收到，已修正
