### ISSUE TITLE
OptimisticLockerPlugin如何使用以及可能的bug

### ISSUE THREAD

**Issue by linlinjava** [itfsw/mybatis-generator-plugin#39]
最近准备采用乐观锁插件解决并发控制。
使用过程中发现一些问题。

1. 当前OptimisticLockerPlugin的使用方法如下描述：
```
<xml>
    <!-- 乐观锁插件 -->
    <plugin type="com.itfsw.mybatis.generator.plugins.OptimisticLockerPlugin">
        <!-- 是否启用自定义nextVersion, 默认不启用使用(使用sql的 set column = column + 1) -->
        <property name="customizedNextVersion" value="true"/>
    </plugin>
    
    <table tableName="tb">
        <!-- 这里可以单独表配置，覆盖全局配置 -->
        <property name="customizedNextVersion" value="false"/>
        <!-- 指定版本列 -->
        <property name="versionColumn" value="version"/>
    </table>
</xml>
```

这里customizedNextVersion到底是什么以及如何使用不是很明白。

2.  按照本人的理解，认为只要启动插件，即可自动生成相关代码。
因此采用如下配置
```
<xml>
    <!-- 乐观锁插件 -->
    <plugin type="com.itfsw.mybatis.generator.plugins.OptimisticLockerPlugin">
    </plugin>
</xml>
```
然后，实际上没有任何反应，没有代码生成。

因此，我这里采用如下配置
```
<xml>
    <!-- 乐观锁插件 -->
    <plugin type="com.itfsw.mybatis.generator.plugins.OptimisticLockerPlugin">
    </plugin>
    
    <table tableName="tb">
        <property name="versionColumn" value="version"/>
    </table>
</xml>
```
这里，项目自动生成了乐观锁的相关代码。
因此，这里的使用方法到底是什么样的。是插件只是开启功能，在表配置中声明才能使用？

3. 此外，还有一个与设想不一致的现象是，我这里多个表，但是只有表一采用了配置，而其他表没有采用配置。
```
<xml>
    <!-- 乐观锁插件 -->
    <plugin type="com.itfsw.mybatis.generator.plugins.OptimisticLockerPlugin">
    </plugin>
    
    <table tableName="tb">
        <property name="versionColumn" value="version"/>
    </table>
    <table tableName="tb2">
    </table>
</xml>
```
我预期是只有表一会生成相关代码，而其他表不会生成代码。
但是实际结果是表一和表二都会生成代码。
因此，个人觉得这里可能是插件代码bug，也可能是设计上不是很合理。

由于这里的问题，我目前是暂缓乐观锁插件的使用。

4. 目前本人开源项目使用mybatis框架，以及作者这里的相关插件。
不知道作者有没有qq或者微信，可以有机会实时沟通一些使用中的问题。
本人也可以帮忙测试以及反馈使用中的问题。

**Comment by linlinjava** [comment]
补充当前一些配置信息：
1. 使用的当前插件1.2.6版本。（因为之后版本还有问题，见 #36）
2. 数据库是MySQL

**Comment by itfsw** [comment]
1. customizedNextVersion 的作用是覆盖插件默认行为，即使用sql的“set column = column + 1“，至于开启customizedNextVersion = true, 文档下方有例子，即需要用户自己使用版本生成逻辑，在发生版本变化是否使用model的nextVersion()方法传入版本号。
2. 你提到的问题3，应该是我代码中使用了错误的变量作用域导致没有清空，我先确认下。

**Comment by linlinjava** [comment]
好的，感谢作者。

现在我个人项目使用你的插件来进行mybatis开发。
最近希望release 1.0版本，希望作者可以帮忙修复我发现的两个issue，多谢多谢：）

**Comment by itfsw** [comment]
[V1.2.10](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.2.10)已修正
