### ISSUE TITLE
batchUpsert

### ISSUE THREAD

**Issue by zzy789264** [itfsw/mybatis-generator-plugin#44]
假设数据库中存在两条数据，修改两条数据（主键不变）再进行batchUpsert会返回结果为4

**Comment by itfsw** [comment]
这个是正常现象，Mysql执行insert或者update返回的数量其实是受影响的行数。
对于upsert(即ON DUPLICATE KEY UPDATE）会存在以下几种可能，
1. 没有主键冲突，对应执行insert此时返回受影响的行数为1；
2.发生主键冲突，对应执行ON DUPLICATE KEY UPDATE的update，此时返回受影响的行数为2（这也是目前我也比较疑惑的地方，按理应该是1的，但mysql就是返回了2）；
3.发生主键冲突，对应执行ON DUPLICATE KEY UPDATE的update（和其他update一样，如果update里面的数据和原始数据一致，即没有产生更新）此时返回受影响的行数为0；

所以综上，对于batchUpsert来说返回结果是无用的。但是对于upsert来说其实是可以根据其结果区分具体执行情况。
