### ISSUE TITLE
怎么不添加 一对一,一对多联表查询的支持

### ISSUE THREAD

**Issue by shyding** [itfsw/mybatis-generator-plugin#47]
关联查询这种

**Comment by itfsw** [comment]
这个问题之前也有人提出过，但是我觉得官方插件的意图还是集中在单表查询的优化上，而且对于多表的操作，其实个人建议使用sql语句更能明确查询目的，也更便于进行sql优化。
后续还是要看官方的支持态度上，之前也做过类似插件，但是都会涉及侵入官方代码所以作废了。

**Comment by shyding** [comment]
package com.biyueyun.common.plugin;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.mybatis.generator.api.GeneratedJavaFile;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.DefaultJavaFormatter;
import org.mybatis.generator.api.dom.java.CompilationUnit;

import com.biyueyun.common.plugin.compoment.DynamicSqlSupportClassGenerator;

import lombok.NoArgsConstructor;


/**
 * Mybatis generator plugin to add dynamic sql table definitions.
 */
@NoArgsConstructor
public class DynamicSqlPlugin extends BasePlugin {
	public static final String TABLE_CLASS_SUFFIX = "tableClassSuffix";
	public static final String ADD_ALIASED_COLUMNS = "addAliasedColumns";
	public static final String ADD_TABLE_ALIAS = "addTableAlias";
	public static final String TABLE_ALIAS_FIELD_NAME = "tableAliasFieldName";

	public static final String DEFAULT_TABLE_ALIAS_FIELD = "tableAlias";

	private String tableClassSuffix;
	private boolean addAliasedColumns;
	private boolean addTableAlias;
	private String tableAliasFieldName;

	@Override
	public boolean validate(List<String> warnings) {
		tableClassSuffix = properties.getProperty(TABLE_CLASS_SUFFIX);
		String addAliasedColumnsString = properties.getProperty(ADD_ALIASED_COLUMNS);
		String addTableAliasString = properties.getProperty(ADD_TABLE_ALIAS);
		tableAliasFieldName = properties.getProperty(TABLE_ALIAS_FIELD_NAME);

		tableClassSuffix = tableClassSuffix == null ? "" : tableClassSuffix.trim();
		addAliasedColumns = Boolean.parseBoolean(addAliasedColumnsString);
		addTableAlias = Boolean.parseBoolean(addTableAliasString);
		if (StringUtils.isBlank(tableAliasFieldName)) {
			tableAliasFieldName = DEFAULT_TABLE_ALIAS_FIELD;
		}

		return true;
	}

	@Override
	public List<GeneratedJavaFile> contextGenerateAdditionalJavaFiles(IntrospectedTable introspectedTable) {
		List<GeneratedJavaFile> models = new ArrayList<>();

		CompilationUnit unit = DynamicSqlSupportClassGenerator
				.of(introspectedTable, context.getCommentGenerator(), tableClassSuffix, addAliasedColumns, addTableAlias, tableAliasFieldName, properties)
				.generate();

		GeneratedJavaFile dynamicSqlModel =
				new GeneratedJavaFile(unit, context.getJavaClientGeneratorConfiguration().getTargetProject(), new DefaultJavaFormatter());

		models.add(dynamicSqlModel);

		return models;
	}

}

**Comment by shyding** [comment]
<dependency>
  <groupId>org.mybatis.dynamic-sql</groupId>
  <artifactId>mybatis-dynamic-sql</artifactId>
  <version>1.1.0</version>
</dependency>

**Comment by shyding** [comment]
<dependency>
  <groupId>org.mybatis.dynamic-sql</groupId>
  <artifactId>mybatis-dynamic-sql</artifactId>
  <version>1.1.0</version>
</dependency>

**Comment by shyding** [comment]
多表查询插件,是否可以通过 官方的这个        <dependency>
  <groupId>org.mybatis.dynamic-sql</groupId>
  <artifactId>mybatis-dynamic-sql</artifactId>
  <version>1.1.0</version>
</dependency>
 依赖,来实现,可以做到不侵入 mgb 源码!
