### ISSUE TITLE
插件com.itfsw.mybatis.generator.plugins.SelectSelectivePlugin插件需配合com.itfsw.mybatis.generator.plugins.ModelColumnPlugin插件使用！

### ISSUE THREAD

**Issue by kid1412621** [itfsw/mybatis-generator-plugin#48]
~~example 类能否支持 lombok ?~~
支持,只是和 lombok 的风格有点区别

**Comment by kid1412621** [comment]
我想用 lombok ,不用 ModelColumnPlugin 插件 , 但我又想用SelectSelectivePlugin 插件

**Comment by itfsw** [comment]
请使用 [Example Criteria 增强插件（ExampleEnhancedPlugin）](https://github.com/itfsw/mybatis-generator-plugin#4-example-%E5%A2%9E%E5%BC%BA%E6%8F%92%E4%BB%B6exampleandiforderby)，增加了example()和andIf()方法，这样就不会打乱链式调用了。

**Comment by kid1412621** [comment]
> 请使用 [Example Criteria 增强插件（ExampleEnhancedPlugin）](https://github.com/itfsw/mybatis-generator-plugin#4-example-%E5%A2%9E%E5%BC%BA%E6%8F%92%E4%BB%B6exampleandiforderby)，增加了 example() 和 andIf() 方法，这样就不会打乱链式调用了。

嗯,这个我使用了,我需要查询结果选择性返回,筛选查询字段的功能.

**Comment by itfsw** [comment]
[查询结果选择性返回插件（SelectSelectivePlugin）](https://github.com/itfsw/mybatis-generator-plugin#15-%E6%9F%A5%E8%AF%A2%E7%BB%93%E6%9E%9C%E9%80%89%E6%8B%A9%E6%80%A7%E8%BF%94%E5%9B%9E%E6%8F%92%E4%BB%B6)这个可以筛选需要返回的字段
