### ISSUE TITLE
可以提供一个生成中文注释的插件吗？

### ISSUE THREAD

**Issue by zhangmz0223** [itfsw/mybatis-generator-plugin#5]
Mybatis Generator 默认生成的注释并不好用。
这需求还是蛮符合国人的。

**Comment by itfsw** [comment]
自定义注释插件已实现你所需要的功能，请测试使用，感谢你的建议[Mybatis Generator Plugin Realease 1.0.11](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.0.11)；
