### ISSUE TITLE
 ${env.JAVA_HOME}/lib/tools.jar error

### ISSUE THREAD

**Issue by chubinzheng** [itfsw/mybatis-generator-plugin#60]
Errors occurred while build effective model from /Users/zhengchubin/.gradle/caches/modules-2/files-2.1/com.itfsw/mybatis-generator-plugin/1.2.12/dd80289cfff720f2503bf170ae13198999fb939a/mybatis-generator-plugin-1.2.12.pom:
    'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar in com.itfsw:mybatis-generator-plugin:1.2.12

**Comment by itfsw** [comment]
无法复现

**Comment by chubinzheng** [comment]
我采用gradle插件会报以上错误，使用def itfswMybatisGeneratorPlugin = 'com.itfsw:mybatis-generator-plugin:1.1.2'，旧版本没有依赖tools.java。则能正常使用

**Comment by itfsw** [comment]
单元测试的时候用了，后续去掉该依赖
