### ISSUE TITLE
18. 表重命名配置插件生成的大小写错误

### ISSUE THREAD

**Issue by MistRay** [itfsw/mybatis-generator-plugin#63]
生成文件名称大小写错误
例如表名为:t_repay_detail
希望得到文件名为:RepayDetail,RepayDetailMapper
实际得到文件名为:Repaydetail,RepaydeailMapper

**Comment by itfsw** [comment]
这个是官方的BUG。  
因为官方新版本自己实现了domainObjectRenamingRule，所以新版插件只是提供一个简化和可配置操作，方便进行全局管理。但底层实现已经是使用官方的逻辑。
如果你比较介意这种写法，你可以使用老版本的那个[Table重命名插件](https://github.com/itfsw/mybatis-generator-plugin#12-table%E9%87%8D%E5%91%BD%E5%90%8D%E6%8F%92%E4%BB%B6)
