### ISSUE TITLE
请问++/--功能能否有不依赖于lombok的方式?

### ISSUE THREAD

**Issue by greydesolate** [itfsw/mybatis-generator-plugin#64]
因为在老的平台进行二次开发,还没有使用lombok,但是想用++/--的功能有些不便.

**Comment by itfsw** [comment]
Lombok是可选插件，可以不使用的。而且Lombok插件使用了新的@SuperBuilder特性，好多IDE工具目前的支持都不好，所以该插件只是因为某些lombok使用者提出来才加上去的。
