### ISSUE TITLE
考虑支持注解方式，目前只支持 XML

### ISSUE THREAD

**Issue by endink** [itfsw/mybatis-generator-plugin#71]

**Comment by zhangxiangfeng** [comment]
关于注解的，我实现了支持了一些（因为我们全是基于注解的），但是代码和我们公司框架耦合性严重，需要的话私聊分享给你下，便于提供思路给你。

**Comment by itfsw** [comment]
很感谢你的支持，目前我们公司主力数据库已经迁移到Elasticsearch和MongoDB，这个项目目前只做BUG维护了，如果你有兴趣继续开发，你可以新开一个项目，谢谢 :)
