### ISSUE TITLE
batchInsertSelective无法插入！！

### ISSUE THREAD

**Issue by zzy789264** [itfsw/mybatis-generator-plugin#73]
![45bf54fabc74b3480ed1c7a58f7520b](https://user-images.githubusercontent.com/26306702/53215107-25424e80-368a-11e9-9020-e7255f20cc74.png)
![8999576f8bd6ee7bf7c19b579991d3a](https://user-images.githubusercontent.com/26306702/53215115-27a4a880-368a-11e9-9242-d4b3d78e755a.png)
![5c44c1e4eb0d0f85649881aa0b9d934](https://user-images.githubusercontent.com/26306702/53215116-28d5d580-368a-11e9-8d85-c11a56eb7d38.png)
![a45a7a30a81c3f0e248f480ad630682](https://user-images.githubusercontent.com/26306702/53215119-2b382f80-368a-11e9-8343-677c0836b3cd.png)

**Comment by itfsw** [comment]
插件生成的batchInsertSelective方法在使用时必须指定selective列，因为插件本身是预编译生成sql,对于批量数据是无法提供类似insertSelective非空插入的方式的;
如需要类似insertSelective非空插入的方式请循环调用insertSelective。  
如只是需要指定插入列请参照[指定列方式](https://github.com/itfsw/mybatis-generator-plugin/blob/master/README.md#10-selective%E9%80%89%E6%8B%A9%E6%8F%92%E5%85%A5%E6%9B%B4%E6%96%B0%E5%A2%9E%E5%BC%BA%E6%8F%92%E4%BB%B6)
