### ISSUE TITLE
batchUpsert 自增key id没判断空

### ISSUE THREAD

**Issue by autostu** [itfsw/mybatis-generator-plugin#77]
plugin 1.3.0

batchUpsert
```
 on duplicate key update 
 id = values(id),
```
upsert
```
 on duplicate key update 
    <trim suffixOverrides=",">
<if test="id != null">
        id = #{id,jdbcType=BIGINT},
      </if>
```

**Comment by itfsw** [comment]
批量的时候是不需要去判断自增key id的，进入update流程的时候代入已有id不影响执行结果。但是这个插件的两个batch方法是有点问题。
第一是batchUpsert里面对自增key这个判断应该删除对自增key的判断，不然会导致values个数不对。
第二是batchUpsertSelective的update方法多删除了自增字段。
