### ISSUE TITLE
增量插件和 lombok 插件不兼容

### ISSUE THREAD

**Issue by kid1412621** [itfsw/mybatis-generator-plugin#78]
使用了增量插件后，生成的 bean 没了 @Builder 注解，取而代之的是一个 生成代码的 builder 。
我知道增量插件的实现需要它，有可能还是用 lombok 的注解， 增量的选择参数那个放到 Column 里？

**Comment by itfsw** [comment]
新版[V1.3.3](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.3.3)已解决
