### ISSUE TITLE
BindingException: Invalid bound statement (not found)

### ISSUE THREAD

**Issue by idlesummerbreeze** [itfsw/mybatis-generator-plugin#80]
请问，使用批量插入的时候总是报这个错误，数据库是SQL Server 。这个是什么原因呢

**Comment by idlesummerbreeze** [comment]
对了忘了说了，我使用的是annotation定义的模型

**Comment by idlesummerbreeze** [comment]
生成的代码是下面这个样子的

`    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Durchfuehrungsweg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Durchfuehrungsweg> list);`

**Comment by itfsw** [comment]
不好意思，SQL Server暂时没有测试，目前插件的测试用例都是基于Mysql的，某些功能可能Sql Sever不支持
