### ISSUE TITLE
分页插件的offset和rows的注释怎么关闭

### ISSUE THREAD

**Issue by rhwayfun** [itfsw/mybatis-generator-plugin#81]

**Comment by itfsw** [comment]
你是需要单独关闭这个插件的注释？ #82 
如果是关闭所有注释mybatis generator配置中就可以关闭（因为才看到你的pull我没有验证是否是你在mybatis generator关闭了而插件还是继续生成注释，那应该是所有插件都有这个bug，五一之后我再统一修改）。
如果你是需要单独某个插件或者某个方法进行关闭，请参照[CommentPlugin](https://github.com/itfsw/mybatis-generator-plugin#13-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E6%8F%92%E4%BB%B6)基于freemarker语法就可精确实现自定义注释。
因为单独关闭某个插件的注释应该不是一个常见的用法，所以不建议为插件增加一个配置项，感谢你的反馈。

**Comment by mlkui** [comment]
@itfsw 

> 如果是关闭所有注释mybatis generator配置中就可以关闭（因为才看到你的pull我没有验证是否是你在mybatis generator关闭了而插件还是继续生成注释，那应该是所有插件都有这个bug，五一之后我再统一修改）。

是有这个问题。

**Comment by rhwayfun** [comment]
@itfsw 
需求其实很简单，在mybatis generator配置了关闭所有注释

`
<commentGenerator> 
<property name="suppressAllComments" value="true"/> 
</commentGenerator>
`

但是使用分页插件后发现offset和rows却有注释，需要不显示注释。看代码后，生成的注释是无条件的，所以提了这个PR。谢谢

**Comment by itfsw** [comment]
[【V1.3.2】](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.3.2)已修正
