### ISSUE TITLE
a = 3 and ( b like foo or c like foo or d like foo)，类似这种条件查询，有更好的实现么？

### ISSUE THREAD

**Issue by luckywinds** [itfsw/mybatis-generator-plugin#85]

**Comment by itfsw** [comment]
目前插件对这种复杂查询都没有太好的解决办法，最近看到mybatis官方推出了[MyBatis Dynamic SQL](http://www.mybatis.org/mybatis-dynamic-sql/docs/introduction.html),不清楚是否有这种实现。

**Comment by weisong5653** [comment]
可以在需要的example里自己代码进去
`public Criteria andOrModelEqual(String condition1, String condition2, String value) {
            addCriterion("(" + condition1 + " = \"" + value + "\" or " + condition2 + " = \"" + value + "\")");
            return (Criteria) this;
        }`
