### ISSUE TITLE
tinyint转成byte很不方便

### ISSUE THREAD

**Issue by yogaling** [itfsw/mybatis-generator-plugin#86]
考虑到用枚举，每次变更的时候，需要去修改表字段，所以很多类型都使用的tinyint存储状态类型等常量值，而tinyint接收的java对象，现在默认是byte，在使用的时候非常不方便，希望能够支持JavaTypeResoulver个性化配置。

**Comment by itfsw** [comment]
可以使用columnOverride
```xml
<table tableName="tb">
        <columnOverride column="status" javaType="java.lang.Short"/>
</table>
```
而且如果使用[状态枚举生成插件（EnumTypeStatusPlugin）](https://github.com/itfsw/mybatis-generator-plugin#21-%E7%8A%B6%E6%80%81%E6%9E%9A%E4%B8%BE%E7%94%9F%E6%88%90%E6%8F%92%E4%BB%B6)就算是byte其实使用也挺方便的
