### ISSUE TITLE
LombokPlugin的@Accessors(chain = true)注解不生成

### ISSUE THREAD

**Issue by tanshion** [itfsw/mybatis-generator-plugin#87]
<plugin type="com.itfsw.mybatis.generator.plugins.LombokPlugin">
			<property name="@Accessors(chain = true)" value="true"/>
			<property name="@Data" value="true"/>
</plugin>

@Accessors(chain = true)注解不生成

**Comment by itfsw** [comment]
新版[V1.3.3](https://github.com/itfsw/mybatis-generator-plugin/releases/tag/V1.3.3)已解决
