### ISSUE TITLE
能提供完整使用该项目的例子吗？？？

### ISSUE THREAD

**Issue by ceohui** [itfsw/mybatis-generator-plugin#90]
老大，能提供完整使用该项目的例子吗？？？

**Comment by ceohui** [comment]
目前github上的还是看不懂啊

**Comment by itfsw** [comment]
配置方面建议参考[MyBatis Generator](http://www.mybatis.org/generator/)官方文档，具体插件作用在每个插件的说明里都提供了使用说明。
