### ISSUE TITLE
selectByExampleSelective有下划线的字段总返回空

### ISSUE THREAD

**Issue by BobooDo** [itfsw/mybatis-generator-plugin#92]
假如某张表中有一字段叫my_name， 在默认情况，也就是Mybatis Generator的驼峰风格打开时，数据表my_name字段会成为java实体类中的myName属性，用selectByExampleSelective返回值时，my_name的字段总返回空。而selectByExample（没有Selective）方法没有问题。

**Comment by itfsw** [comment]
无法复现你所描述的问题呢，你是否没有在查询方法中selective参数中没有包含该字段呢？
```java
tbMapper.selectByExampleSelective(null, Tb.Column.id, Tb.Column.myName)
```
