### ISSUE TITLE
 查询结果选择性返回插件 不生效

### ISSUE THREAD

**Issue by nkyy5** [itfsw/mybatis-generator-plugin#97]
添加     查询结果选择性返回插件
    plugin type="com.itfsw.mybatis.generator.plugins.SelectSelectivePlugin" 
到 xml 里面没有生效。。。
我添加 Example增强插件 和 MySQL分页插件 却有效

**Comment by itfsw** [comment]
需要配合[ModelColumnPlugin](https://github.com/itfsw/mybatis-generator-plugin#8-%E6%95%B0%E6%8D%AEmodel%E5%B1%9E%E6%80%A7%E5%AF%B9%E5%BA%94column%E8%8E%B7%E5%8F%96%E6%8F%92%E4%BB%B6)使用
